version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      MEMORY: "4G"
      VERSION: "1.20.1w"
      TYPE: "CUSTOM"
      CUSTOM_SERVER: "/data/versions/spigot-1.20.1.jar"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data